name: Release
on:
    release:
        types: [created]

jobs:
    releases-matrix:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                goos: [linux, windows, darwin]
                goarch: [amd64, arm64]
                exclude:
                    - goarch: arm64
                      goos: windows

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v3
              with:
                  go-version: "1.23"
            - name: Build
              env:
                  GOOS: ${{ matrix.goos }}
                  GOARCH: ${{ matrix.goarch }}
                  VERSION: ${{ github.event.release.tag_name }}
              run: |
                  go build -ldflags "-X github.com/chunkifydev/cli/pkg/version.Version=${VERSION}" -o chunkify
                  tar -czf chunkify.tar.gz chunkify
            - name: Upload
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ./chunkify.tar.gz
                  asset_name: chunkify_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz
                  asset_content_type: application/gzip
