name: Test
on:
    push:
        branches: [main, v2]
    pull_request:
        branches: [main, v2]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: "1.23.x"
                  check-latest: true
            - name: Get latest chunkify-go dependency
              run: |
                  cd ..
                  git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/chunkifydev/chunkify-go.git
                  cd chunkify-go
                  git checkout main
            - name: Download dependencies
              run: go mod download
            - name: Run tests
              run: |
                  go test ./...
