name: Test
on:
    push:
        branches: [main, v2]
    pull_request:
        branches: [main, v2]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: "1.23.x"
                  check-latest: true
            - name: Get latest chunkify-go dependency
              uses: actions/checkout@v4
              with:
                  repository: chunkifydev/chunkify-go
                  path: ../chunkify-go
                  ref: main
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Download dependencies
              run: go mod download
            - name: Run tests
              run: |
                  go test ./...
